### PR TITLE
Added cli argument for logFile, tests and fix for #21

### LINKED ISSUE #21: Off by one problem
With the current master, I get complains from JSON.parse because the message contains an additional character.

### PR DESCRIPTION
**Pull request by svenefftinge**
fixes #21

### CODE REVIEW

**Comment by svenefftinge** [comment]
I intend to work a bit more on this and to make turnarounds faster for me I'll go with fork for now. Please let me know if and how you would prefer to collaborate.

**Comment by prabirshrestha** [comment]
@svenefftinge I'm all for collaborating, but have been busy with moving so haven't had a chance to look at this PR or others. Feel free to open it.

It would be good to break the PR into multiple PRs. One of just add logFile, other to add test and so on.

**Comment by svenefftinge** [comment]
I have lots of changes and would like to move a bit quicker. 
So, maybe I just work on my fork and when you find time we can discuss if you like my changes and we work together again.

**Comment by svenefftinge** [comment]
Hi @prabirshrestha, I wanted to let you know that I started afresh. For one because I changed so much, that a merge would not have made much sense, but also because the copyright part of your work was not really clear (and I have to be careful, there). 

However, the basic ideas and concepts are still very close to what you did here (i.e. wrapping tsserver). The current state has already quite some improvements (e.g.  diagnostics, resolved hovers and completions, incremental editing support) and we will keep working on it in the coming weeks, to make it more complete.

I noticed from comments you made in other repos, that you did this more for verifying whether the sourcegraph typescript language server is slow or not. Anyway, I wanted to say that you did a great job and I would be happy to see contributions from your side. I put an attribution on the readme. I hope that is fine with you and if not please let me know.

repo: https://github.com/theia-ide/typescript-lsp

**Comment by prabirshrestha** [comment]
@svenefftinge That is awesome. I have too many OSS repos so I'm always happy when someone takes over and makes it better. Will give it a try today and see how it works. If it works I can update README saying my package is deprecated and point to your repo.

Let me know if you would like to own the `typescript-language-server` npm package. I would be happy to hand it over to you.

**Comment by svenefftinge** [comment]
Great and thanks for the PR. I have only tested on mac with https://github.com/theia-ide/theia. Let me know how it works with your vim https://github.com/prabirshrestha/vim-lsp

**Comment by svenefftinge** [comment]
Also, thanks for offering the npm package. Yes, I think that is a better name and I would be happy to use it.

**Comment by prabirshrestha** [comment]
@svenefftinge I have given you access to the npm package. https://www.npmjs.com/package/typescript-language-server

I have also already added deprecation warning in https://github.com/prabirshrestha/typescript-language-server. If you are changing your repo name let me know so that I can point to the correct link. Feel free to remove me from the npm package if you would like too.

Also might want to update so it points to the new repository. https://github.com/Microsoft/language-server-protocol/wiki/Protocol-Implementations

**Comment by svenefftinge** [comment]
Ok, great. Did you try it out in vim? Does it work for you?

**Comment by svenefftinge** [comment]
Btw assuming you are on windows, there is an issue with the new `tsserver` lookup strategy.
See https://github.com/theia-ide/typescript-lsp/issues/2#issuecomment-333490215

**Comment by svenefftinge** [comment]
I now renamed the package and the repo to `typescript-language-server` and published the current state as 0.1.0.

**Comment by prabirshrestha** [comment]
@svenefftinge awesome. I posted the windows solution at https://github.com/theia-ide/typescript-language-server/issues/2#issuecomment-333638546. Should be an easy fix.

**Pull request closed without merging**
